#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYonetim.App_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OnikimGorev")]
	public partial class GorevDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEMail(EMail instance);
    partial void UpdateEMail(EMail instance);
    partial void DeleteEMail(EMail instance);
    partial void InsertGorevHareket(GorevHareket instance);
    partial void UpdateGorevHareket(GorevHareket instance);
    partial void DeleteGorevHareket(GorevHareket instance);
    partial void InsertTanim(Tanim instance);
    partial void UpdateTanim(Tanim instance);
    partial void DeleteTanim(Tanim instance);
    partial void InsertKullanici(Kullanici instance);
    partial void UpdateKullanici(Kullanici instance);
    partial void DeleteKullanici(Kullanici instance);
    partial void InsertAyar(Ayar instance);
    partial void UpdateAyar(Ayar instance);
    partial void DeleteAyar(Ayar instance);
    partial void InsertGorevCalisma(GorevCalisma instance);
    partial void UpdateGorevCalisma(GorevCalisma instance);
    partial void DeleteGorevCalisma(GorevCalisma instance);
    partial void InsertEkDosya(EkDosya instance);
    partial void UpdateEkDosya(EkDosya instance);
    partial void DeleteEkDosya(EkDosya instance);
    partial void InsertGorevler(Gorevler instance);
    partial void UpdateGorevler(Gorevler instance);
    partial void DeleteGorevler(Gorevler instance);
    partial void InsertTatilGunleri(TatilGunleri instance);
    partial void UpdateTatilGunleri(TatilGunleri instance);
    partial void DeleteTatilGunleri(TatilGunleri instance);
    partial void InsertMusteri(Musteri instance);
    partial void UpdateMusteri(Musteri instance);
    partial void DeleteMusteri(Musteri instance);
    partial void InsertProjeForm(ProjeForm instance);
    partial void UpdateProjeForm(ProjeForm instance);
    partial void DeleteProjeForm(ProjeForm instance);
    #endregion
		
		public GorevDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OnikimGorevConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GorevDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GorevDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GorevDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GorevDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EMail> EMails
		{
			get
			{
				return this.GetTable<EMail>();
			}
		}
		
		public System.Data.Linq.Table<GorevHareket> GorevHarekets
		{
			get
			{
				return this.GetTable<GorevHareket>();
			}
		}
		
		public System.Data.Linq.Table<Tanim> Tanims
		{
			get
			{
				return this.GetTable<Tanim>();
			}
		}
		
		public System.Data.Linq.Table<Kullanici> Kullanicis
		{
			get
			{
				return this.GetTable<Kullanici>();
			}
		}
		
		public System.Data.Linq.Table<Ayar> Ayars
		{
			get
			{
				return this.GetTable<Ayar>();
			}
		}
		
		public System.Data.Linq.Table<GorevCalisma> GorevCalismas
		{
			get
			{
				return this.GetTable<GorevCalisma>();
			}
		}
		
		public System.Data.Linq.Table<EkDosya> EkDosyas
		{
			get
			{
				return this.GetTable<EkDosya>();
			}
		}
		
		public System.Data.Linq.Table<Gorevler> Gorevlers
		{
			get
			{
				return this.GetTable<Gorevler>();
			}
		}
		
		public System.Data.Linq.Table<TatilGunleri> TatilGunleris
		{
			get
			{
				return this.GetTable<TatilGunleri>();
			}
		}
		
		public System.Data.Linq.Table<Musteri> Musteris
		{
			get
			{
				return this.GetTable<Musteri>();
			}
		}
		
		public System.Data.Linq.Table<ProjeForm> ProjeForms
		{
			get
			{
				return this.GetTable<ProjeForm>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ong.Gorevi_YenidenSirala")]
		public int Gorevi_YenidenSirala([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sorumlu", DbType="VarChar(5)")] string sorumlu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GorevID", DbType="Int")] System.Nullable<int> gorevID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MevcutSira", DbType="Int")] System.Nullable<int> mevcutSira, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YeniSira", DbType="Int")] System.Nullable<int> yeniSira, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SadeceSirala", DbType="Bit")] System.Nullable<bool> sadeceSirala)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sorumlu, gorevID, mevcutSira, yeniSira, sadeceSirala);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ong.GorevCalisma_Takvimi")]
		public ISingleResult<GorevCalisma_TakvimiResult> GorevCalisma_Takvimi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BaslangicTarih", DbType="Date")] System.Nullable<System.DateTime> baslangicTarih, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BitisTarih", DbType="Date")] System.Nullable<System.DateTime> bitisTarih)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), baslangicTarih, bitisTarih);
			return ((ISingleResult<GorevCalisma_TakvimiResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.EMail")]
	public partial class EMail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MailTo;
		
		private string _MailCc;
		
		private string _Baslik;
		
		private string _Icerik;
		
		private string _Kaydeden;
		
		private System.Nullable<System.DateTime> _KayitTarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMailToChanging(string value);
    partial void OnMailToChanged();
    partial void OnMailCcChanging(string value);
    partial void OnMailCcChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihChanged();
    #endregion
		
		public EMail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTo", DbType="VarChar(300)")]
		public string MailTo
		{
			get
			{
				return this._MailTo;
			}
			set
			{
				if ((this._MailTo != value))
				{
					this.OnMailToChanging(value);
					this.SendPropertyChanging();
					this._MailTo = value;
					this.SendPropertyChanged("MailTo");
					this.OnMailToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailCc", DbType="VarChar(300)")]
		public string MailCc
		{
			get
			{
				return this._MailCc;
			}
			set
			{
				if ((this._MailCc != value))
				{
					this.OnMailCcChanging(value);
					this.SendPropertyChanging();
					this._MailCc = value;
					this.SendPropertyChanged("MailCc");
					this.OnMailCcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="VarChar(300)")]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="VarChar(4000)")]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.GorevHareket")]
	public partial class GorevHareket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _GorevID;
		
		private string _Firma;
		
		private string _Proje;
		
		private string _Form;
		
		private string _Sorumlu;
		
		private string _Gorev;
		
		private string _Aciklama;
		
		private string _DurumAciklama;
		
		private string _Oncelik;
		
		private System.Nullable<short> _Durum;
		
		private string _DurumStr;
		
		private System.Nullable<System.DateTime> _TahminiBitisTarih;
		
		private string _Kaydeden;
		
		private System.DateTime _KayitTarih;
		
		private string _SqlType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGorevIDChanging(int value);
    partial void OnGorevIDChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnProjeChanging(string value);
    partial void OnProjeChanged();
    partial void OnFormChanging(string value);
    partial void OnFormChanged();
    partial void OnSorumluChanging(string value);
    partial void OnSorumluChanged();
    partial void OnGorevChanging(string value);
    partial void OnGorevChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnDurumAciklamaChanging(string value);
    partial void OnDurumAciklamaChanged();
    partial void OnOncelikChanging(string value);
    partial void OnOncelikChanged();
    partial void OnDurumChanging(System.Nullable<short> value);
    partial void OnDurumChanged();
    partial void OnDurumStrChanging(string value);
    partial void OnDurumStrChanged();
    partial void OnTahminiBitisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTahminiBitisTarihChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.DateTime value);
    partial void OnKayitTarihChanged();
    partial void OnSqlTypeChanging(string value);
    partial void OnSqlTypeChanged();
    #endregion
		
		public GorevHareket()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorevID", DbType="Int NOT NULL")]
		public int GorevID
		{
			get
			{
				return this._GorevID;
			}
			set
			{
				if ((this._GorevID != value))
				{
					this.OnGorevIDChanging(value);
					this.SendPropertyChanging();
					this._GorevID = value;
					this.SendPropertyChanged("GorevID");
					this.OnGorevIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(20)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proje", DbType="VarChar(20)")]
		public string Proje
		{
			get
			{
				return this._Proje;
			}
			set
			{
				if ((this._Proje != value))
				{
					this.OnProjeChanging(value);
					this.SendPropertyChanging();
					this._Proje = value;
					this.SendPropertyChanged("Proje");
					this.OnProjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="VarChar(50)")]
		public string Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorumlu", DbType="VarChar(5)")]
		public string Sorumlu
		{
			get
			{
				return this._Sorumlu;
			}
			set
			{
				if ((this._Sorumlu != value))
				{
					this.OnSorumluChanging(value);
					this.SendPropertyChanging();
					this._Sorumlu = value;
					this.SendPropertyChanged("Sorumlu");
					this.OnSorumluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorev", DbType="VarChar(100)")]
		public string Gorev
		{
			get
			{
				return this._Gorev;
			}
			set
			{
				if ((this._Gorev != value))
				{
					this.OnGorevChanging(value);
					this.SendPropertyChanging();
					this._Gorev = value;
					this.SendPropertyChanged("Gorev");
					this.OnGorevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(2000)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumAciklama", DbType="VarChar(2000)")]
		public string DurumAciklama
		{
			get
			{
				return this._DurumAciklama;
			}
			set
			{
				if ((this._DurumAciklama != value))
				{
					this.OnDurumAciklamaChanging(value);
					this.SendPropertyChanging();
					this._DurumAciklama = value;
					this.SendPropertyChanged("DurumAciklama");
					this.OnDurumAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oncelik", DbType="VarChar(20)")]
		public string Oncelik
		{
			get
			{
				return this._Oncelik;
			}
			set
			{
				if ((this._Oncelik != value))
				{
					this.OnOncelikChanging(value);
					this.SendPropertyChanging();
					this._Oncelik = value;
					this.SendPropertyChanged("Oncelik");
					this.OnOncelikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="SmallInt")]
		public System.Nullable<short> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumStr", DbType="VarChar(20)")]
		public string DurumStr
		{
			get
			{
				return this._DurumStr;
			}
			set
			{
				if ((this._DurumStr != value))
				{
					this.OnDurumStrChanging(value);
					this.SendPropertyChanging();
					this._DurumStr = value;
					this.SendPropertyChanged("DurumStr");
					this.OnDurumStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TahminiBitisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TahminiBitisTarih
		{
			get
			{
				return this._TahminiBitisTarih;
			}
			set
			{
				if ((this._TahminiBitisTarih != value))
				{
					this.OnTahminiBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._TahminiBitisTarih = value;
					this.SendPropertyChanged("TahminiBitisTarih");
					this.OnTahminiBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime NOT NULL")]
		public System.DateTime KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqlType", DbType="VarChar(10)")]
		public string SqlType
		{
			get
			{
				return this._SqlType;
			}
			set
			{
				if ((this._SqlType != value))
				{
					this.OnSqlTypeChanging(value);
					this.SendPropertyChanging();
					this._SqlType = value;
					this.SendPropertyChanged("SqlType");
					this.OnSqlTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.Tanim")]
	public partial class Tanim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Tip;
		
		private short _KodInt;
		
		private string _Kod;
		
		private string _Aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipChanging(short value);
    partial void OnTipChanged();
    partial void OnKodIntChanging(short value);
    partial void OnKodIntChanged();
    partial void OnKodChanging(string value);
    partial void OnKodChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    #endregion
		
		public Tanim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Tip
		{
			get
			{
				return this._Tip;
			}
			set
			{
				if ((this._Tip != value))
				{
					this.OnTipChanging(value);
					this.SendPropertyChanging();
					this._Tip = value;
					this.SendPropertyChanged("Tip");
					this.OnTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodInt", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short KodInt
		{
			get
			{
				return this._KodInt;
			}
			set
			{
				if ((this._KodInt != value))
				{
					this.OnKodIntChanging(value);
					this.SendPropertyChanging();
					this._KodInt = value;
					this.SendPropertyChanged("KodInt");
					this.OnKodIntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(100)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.Kullanici")]
	public partial class Kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KulKodu;
		
		private string _Pass;
		
		private string _AdSoyad;
		
		private short _YetkiKod;
		
		private string _Email;
		
		private string _Tel;
		
		private string _Firma;
		
		private short _Type;
		
		private string _Kaydeden;
		
		private System.Nullable<System.DateTime> _KayitTarih;
		
		private string _Degistiren;
		
		private System.Nullable<System.DateTime> _DegisTarih;
		
		private EntitySet<Gorevler> _Gorevlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKulKoduChanging(string value);
    partial void OnKulKoduChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnAdSoyadChanging(string value);
    partial void OnAdSoyadChanged();
    partial void OnYetkiKodChanging(short value);
    partial void OnYetkiKodChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnTypeChanging(short value);
    partial void OnTypeChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihChanged();
    partial void OnDegistirenChanging(string value);
    partial void OnDegistirenChanged();
    partial void OnDegisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnDegisTarihChanged();
    #endregion
		
		public Kullanici()
		{
			this._Gorevlers = new EntitySet<Gorevler>(new Action<Gorevler>(this.attach_Gorevlers), new Action<Gorevler>(this.detach_Gorevlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KulKodu", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string KulKodu
		{
			get
			{
				return this._KulKodu;
			}
			set
			{
				if ((this._KulKodu != value))
				{
					this.OnKulKoduChanging(value);
					this.SendPropertyChanging();
					this._KulKodu = value;
					this.SendPropertyChanged("KulKodu");
					this.OnKulKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdSoyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdSoyad
		{
			get
			{
				return this._AdSoyad;
			}
			set
			{
				if ((this._AdSoyad != value))
				{
					this.OnAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AdSoyad = value;
					this.SendPropertyChanged("AdSoyad");
					this.OnAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiKod", DbType="SmallInt NOT NULL")]
		public short YetkiKod
		{
			get
			{
				return this._YetkiKod;
			}
			set
			{
				if ((this._YetkiKod != value))
				{
					this.OnYetkiKodChanging(value);
					this.SendPropertyChanging();
					this._YetkiKod = value;
					this.SendPropertyChanged("YetkiKod");
					this.OnYetkiKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(80)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(15)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(20)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="SmallInt NOT NULL")]
		public short Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degistiren", DbType="VarChar(5)")]
		public string Degistiren
		{
			get
			{
				return this._Degistiren;
			}
			set
			{
				if ((this._Degistiren != value))
				{
					this.OnDegistirenChanging(value);
					this.SendPropertyChanging();
					this._Degistiren = value;
					this.SendPropertyChanged("Degistiren");
					this.OnDegistirenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DegisTarih
		{
			get
			{
				return this._DegisTarih;
			}
			set
			{
				if ((this._DegisTarih != value))
				{
					this.OnDegisTarihChanging(value);
					this.SendPropertyChanging();
					this._DegisTarih = value;
					this.SendPropertyChanged("DegisTarih");
					this.OnDegisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Gorevler", Storage="_Gorevlers", ThisKey="KulKodu", OtherKey="Sorumlu")]
		public EntitySet<Gorevler> Gorevlers
		{
			get
			{
				return this._Gorevlers;
			}
			set
			{
				this._Gorevlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gorevlers(Gorevler entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = this;
		}
		
		private void detach_Gorevlers(Gorevler entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.Ayar")]
	public partial class Ayar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MailTo;
		
		private string _MailCc;
		
		private System.Nullable<bool> _MailCcTumunde;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMailToChanging(string value);
    partial void OnMailToChanged();
    partial void OnMailCcChanging(string value);
    partial void OnMailCcChanged();
    partial void OnMailCcTumundeChanging(System.Nullable<bool> value);
    partial void OnMailCcTumundeChanged();
    #endregion
		
		public Ayar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTo", DbType="VarChar(300)")]
		public string MailTo
		{
			get
			{
				return this._MailTo;
			}
			set
			{
				if ((this._MailTo != value))
				{
					this.OnMailToChanging(value);
					this.SendPropertyChanging();
					this._MailTo = value;
					this.SendPropertyChanged("MailTo");
					this.OnMailToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailCc", DbType="VarChar(300)")]
		public string MailCc
		{
			get
			{
				return this._MailCc;
			}
			set
			{
				if ((this._MailCc != value))
				{
					this.OnMailCcChanging(value);
					this.SendPropertyChanging();
					this._MailCc = value;
					this.SendPropertyChanged("MailCc");
					this.OnMailCcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailCcTumunde", DbType="Bit")]
		public System.Nullable<bool> MailCcTumunde
		{
			get
			{
				return this._MailCcTumunde;
			}
			set
			{
				if ((this._MailCcTumunde != value))
				{
					this.OnMailCcTumundeChanging(value);
					this.SendPropertyChanging();
					this._MailCcTumunde = value;
					this.SendPropertyChanged("MailCcTumunde");
					this.OnMailCcTumundeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.GorevCalisma")]
	public partial class GorevCalisma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Sorumlular;
		
		private int _GorevID;
		
		private System.DateTime _Tarih1;
		
		private System.Nullable<System.DateTime> _Tarih2;
		
		private int _CalismaSure;
		
		private string _Calisma;
		
		private System.Nullable<short> _Durum;
		
		private string _Kaydeden;
		
		private System.Nullable<System.DateTime> _KayitTarih;
		
		private string _Degistiren;
		
		private System.Nullable<System.DateTime> _DegisTarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSorumlularChanging(string value);
    partial void OnSorumlularChanged();
    partial void OnGorevIDChanging(int value);
    partial void OnGorevIDChanged();
    partial void OnTarih1Changing(System.DateTime value);
    partial void OnTarih1Changed();
    partial void OnTarih2Changing(System.Nullable<System.DateTime> value);
    partial void OnTarih2Changed();
    partial void OnCalismaSureChanging(int value);
    partial void OnCalismaSureChanged();
    partial void OnCalismaChanging(string value);
    partial void OnCalismaChanged();
    partial void OnDurumChanging(System.Nullable<short> value);
    partial void OnDurumChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihChanged();
    partial void OnDegistirenChanging(string value);
    partial void OnDegistirenChanged();
    partial void OnDegisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnDegisTarihChanged();
    #endregion
		
		public GorevCalisma()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorumlular", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Sorumlular
		{
			get
			{
				return this._Sorumlular;
			}
			set
			{
				if ((this._Sorumlular != value))
				{
					this.OnSorumlularChanging(value);
					this.SendPropertyChanging();
					this._Sorumlular = value;
					this.SendPropertyChanged("Sorumlular");
					this.OnSorumlularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorevID", DbType="Int NOT NULL")]
		public int GorevID
		{
			get
			{
				return this._GorevID;
			}
			set
			{
				if ((this._GorevID != value))
				{
					this.OnGorevIDChanging(value);
					this.SendPropertyChanging();
					this._GorevID = value;
					this.SendPropertyChanged("GorevID");
					this.OnGorevIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih1", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Tarih1
		{
			get
			{
				return this._Tarih1;
			}
			set
			{
				if ((this._Tarih1 != value))
				{
					this.OnTarih1Changing(value);
					this.SendPropertyChanging();
					this._Tarih1 = value;
					this.SendPropertyChanged("Tarih1");
					this.OnTarih1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih2", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Tarih2
		{
			get
			{
				return this._Tarih2;
			}
			set
			{
				if ((this._Tarih2 != value))
				{
					this.OnTarih2Changing(value);
					this.SendPropertyChanging();
					this._Tarih2 = value;
					this.SendPropertyChanged("Tarih2");
					this.OnTarih2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalismaSure", DbType="Int NOT NULL")]
		public int CalismaSure
		{
			get
			{
				return this._CalismaSure;
			}
			set
			{
				if ((this._CalismaSure != value))
				{
					this.OnCalismaSureChanging(value);
					this.SendPropertyChanging();
					this._CalismaSure = value;
					this.SendPropertyChanged("CalismaSure");
					this.OnCalismaSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calisma", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string Calisma
		{
			get
			{
				return this._Calisma;
			}
			set
			{
				if ((this._Calisma != value))
				{
					this.OnCalismaChanging(value);
					this.SendPropertyChanging();
					this._Calisma = value;
					this.SendPropertyChanged("Calisma");
					this.OnCalismaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="SmallInt")]
		public System.Nullable<short> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degistiren", DbType="VarChar(5)")]
		public string Degistiren
		{
			get
			{
				return this._Degistiren;
			}
			set
			{
				if ((this._Degistiren != value))
				{
					this.OnDegistirenChanging(value);
					this.SendPropertyChanging();
					this._Degistiren = value;
					this.SendPropertyChanged("Degistiren");
					this.OnDegistirenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DegisTarih
		{
			get
			{
				return this._DegisTarih;
			}
			set
			{
				if ((this._DegisTarih != value))
				{
					this.OnDegisTarihChanging(value);
					this.SendPropertyChanging();
					this._DegisTarih = value;
					this.SendPropertyChanged("DegisTarih");
					this.OnDegisTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.EkDosya")]
	public partial class EkDosya : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _GorevID;
		
		private string _DosyaAdi;
		
		private string _Boyut;
		
		private string _Aciklama;
		
		private string _Kaydeden;
		
		private System.Nullable<System.DateTime> _KayitTarih;
		
		private short _Tip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGorevIDChanging(int value);
    partial void OnGorevIDChanged();
    partial void OnDosyaAdiChanging(string value);
    partial void OnDosyaAdiChanged();
    partial void OnBoyutChanging(string value);
    partial void OnBoyutChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihChanged();
    partial void OnTipChanging(short value);
    partial void OnTipChanged();
    #endregion
		
		public EkDosya()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GorevID", DbType="Int NOT NULL")]
		public int GorevID
		{
			get
			{
				return this._GorevID;
			}
			set
			{
				if ((this._GorevID != value))
				{
					this.OnGorevIDChanging(value);
					this.SendPropertyChanging();
					this._GorevID = value;
					this.SendPropertyChanged("GorevID");
					this.OnGorevIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosyaAdi", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DosyaAdi
		{
			get
			{
				return this._DosyaAdi;
			}
			set
			{
				if ((this._DosyaAdi != value))
				{
					this.OnDosyaAdiChanging(value);
					this.SendPropertyChanging();
					this._DosyaAdi = value;
					this.SendPropertyChanged("DosyaAdi");
					this.OnDosyaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="VarChar(20)")]
		public string Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(500)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip", DbType="SmallInt NOT NULL")]
		public short Tip
		{
			get
			{
				return this._Tip;
			}
			set
			{
				if ((this._Tip != value))
				{
					this.OnTipChanging(value);
					this.SendPropertyChanging();
					this._Tip = value;
					this.SendPropertyChanged("Tip");
					this.OnTipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.Gorevler")]
	public partial class Gorevler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Firma;
		
		private string _Proje;
		
		private string _Form;
		
		private string _Sorumlu;
		
		private string _Sorumlu2;
		
		private string _Sorumlu3;
		
		private string _Gorev;
		
		private string _Aciklama;
		
		private string _DurumAciklama;
		
		private short _Oncelik;
		
		private short _Durum;
		
		private System.Nullable<System.DateTime> _TahminiBitisTarih;
		
		private System.Nullable<System.DateTime> _BitisTarih;
		
		private string _Kaydeden;
		
		private System.DateTime _KayitTarih;
		
		private string _Degistiren;
		
		private System.DateTime _DegisTarih;
		
		private System.Nullable<short> _IslemTip;
		
		private System.Nullable<int> _IslemSira;
		
		private EntityRef<Kullanici> _Kullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnProjeChanging(string value);
    partial void OnProjeChanged();
    partial void OnFormChanging(string value);
    partial void OnFormChanged();
    partial void OnSorumluChanging(string value);
    partial void OnSorumluChanged();
    partial void OnSorumlu2Changing(string value);
    partial void OnSorumlu2Changed();
    partial void OnSorumlu3Changing(string value);
    partial void OnSorumlu3Changed();
    partial void OnGorevChanging(string value);
    partial void OnGorevChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnDurumAciklamaChanging(string value);
    partial void OnDurumAciklamaChanged();
    partial void OnOncelikChanging(short value);
    partial void OnOncelikChanged();
    partial void OnDurumChanging(short value);
    partial void OnDurumChanged();
    partial void OnTahminiBitisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTahminiBitisTarihChanged();
    partial void OnBitisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnBitisTarihChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.DateTime value);
    partial void OnKayitTarihChanged();
    partial void OnDegistirenChanging(string value);
    partial void OnDegistirenChanged();
    partial void OnDegisTarihChanging(System.DateTime value);
    partial void OnDegisTarihChanged();
    partial void OnIslemTipChanging(System.Nullable<short> value);
    partial void OnIslemTipChanged();
    partial void OnIslemSiraChanging(System.Nullable<int> value);
    partial void OnIslemSiraChanged();
    #endregion
		
		public Gorevler()
		{
			this._Kullanici = default(EntityRef<Kullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Proje
		{
			get
			{
				return this._Proje;
			}
			set
			{
				if ((this._Proje != value))
				{
					this.OnProjeChanging(value);
					this.SendPropertyChanging();
					this._Proje = value;
					this.SendPropertyChanged("Proje");
					this.OnProjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorumlu", DbType="VarChar(5)")]
		public string Sorumlu
		{
			get
			{
				return this._Sorumlu;
			}
			set
			{
				if ((this._Sorumlu != value))
				{
					if (this._Kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSorumluChanging(value);
					this.SendPropertyChanging();
					this._Sorumlu = value;
					this.SendPropertyChanged("Sorumlu");
					this.OnSorumluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorumlu2", DbType="VarChar(5)")]
		public string Sorumlu2
		{
			get
			{
				return this._Sorumlu2;
			}
			set
			{
				if ((this._Sorumlu2 != value))
				{
					this.OnSorumlu2Changing(value);
					this.SendPropertyChanging();
					this._Sorumlu2 = value;
					this.SendPropertyChanged("Sorumlu2");
					this.OnSorumlu2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorumlu3", DbType="VarChar(5)")]
		public string Sorumlu3
		{
			get
			{
				return this._Sorumlu3;
			}
			set
			{
				if ((this._Sorumlu3 != value))
				{
					this.OnSorumlu3Changing(value);
					this.SendPropertyChanging();
					this._Sorumlu3 = value;
					this.SendPropertyChanged("Sorumlu3");
					this.OnSorumlu3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorev", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Gorev
		{
			get
			{
				return this._Gorev;
			}
			set
			{
				if ((this._Gorev != value))
				{
					this.OnGorevChanging(value);
					this.SendPropertyChanging();
					this._Gorev = value;
					this.SendPropertyChanged("Gorev");
					this.OnGorevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumAciklama", DbType="VarChar(2000)")]
		public string DurumAciklama
		{
			get
			{
				return this._DurumAciklama;
			}
			set
			{
				if ((this._DurumAciklama != value))
				{
					this.OnDurumAciklamaChanging(value);
					this.SendPropertyChanging();
					this._DurumAciklama = value;
					this.SendPropertyChanged("DurumAciklama");
					this.OnDurumAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oncelik", DbType="SmallInt NOT NULL")]
		public short Oncelik
		{
			get
			{
				return this._Oncelik;
			}
			set
			{
				if ((this._Oncelik != value))
				{
					this.OnOncelikChanging(value);
					this.SendPropertyChanging();
					this._Oncelik = value;
					this.SendPropertyChanged("Oncelik");
					this.OnOncelikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="SmallInt NOT NULL")]
		public short Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TahminiBitisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TahminiBitisTarih
		{
			get
			{
				return this._TahminiBitisTarih;
			}
			set
			{
				if ((this._TahminiBitisTarih != value))
				{
					this.OnTahminiBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._TahminiBitisTarih = value;
					this.SendPropertyChanged("TahminiBitisTarih");
					this.OnTahminiBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> BitisTarih
		{
			get
			{
				return this._BitisTarih;
			}
			set
			{
				if ((this._BitisTarih != value))
				{
					this.OnBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._BitisTarih = value;
					this.SendPropertyChanged("BitisTarih");
					this.OnBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime NOT NULL")]
		public System.DateTime KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degistiren", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Degistiren
		{
			get
			{
				return this._Degistiren;
			}
			set
			{
				if ((this._Degistiren != value))
				{
					this.OnDegistirenChanging(value);
					this.SendPropertyChanging();
					this._Degistiren = value;
					this.SendPropertyChanged("Degistiren");
					this.OnDegistirenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegisTarih", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DegisTarih
		{
			get
			{
				return this._DegisTarih;
			}
			set
			{
				if ((this._DegisTarih != value))
				{
					this.OnDegisTarihChanging(value);
					this.SendPropertyChanging();
					this._DegisTarih = value;
					this.SendPropertyChanged("DegisTarih");
					this.OnDegisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemTip", DbType="SmallInt")]
		public System.Nullable<short> IslemTip
		{
			get
			{
				return this._IslemTip;
			}
			set
			{
				if ((this._IslemTip != value))
				{
					this.OnIslemTipChanging(value);
					this.SendPropertyChanging();
					this._IslemTip = value;
					this.SendPropertyChanged("IslemTip");
					this.OnIslemTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IslemSira", DbType="Int")]
		public System.Nullable<int> IslemSira
		{
			get
			{
				return this._IslemSira;
			}
			set
			{
				if ((this._IslemSira != value))
				{
					this.OnIslemSiraChanging(value);
					this.SendPropertyChanging();
					this._IslemSira = value;
					this.SendPropertyChanged("IslemSira");
					this.OnIslemSiraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Gorevler", Storage="_Kullanici", ThisKey="Sorumlu", OtherKey="KulKodu", IsForeignKey=true, DeleteRule="CASCADE")]
		public Kullanici Kullanici
		{
			get
			{
				return this._Kullanici.Entity;
			}
			set
			{
				Kullanici previousValue = this._Kullanici.Entity;
				if (((previousValue != value) 
							|| (this._Kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kullanici.Entity = null;
						previousValue.Gorevlers.Remove(this);
					}
					this._Kullanici.Entity = value;
					if ((value != null))
					{
						value.Gorevlers.Add(this);
						this._Sorumlu = value.KulKodu;
					}
					else
					{
						this._Sorumlu = default(string);
					}
					this.SendPropertyChanged("Kullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.TatilGunleri")]
	public partial class TatilGunleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Izinliler;
		
		private System.DateTime _Gun;
		
		private string _Aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIzinlilerChanging(string value);
    partial void OnIzinlilerChanged();
    partial void OnGunChanging(System.DateTime value);
    partial void OnGunChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    #endregion
		
		public TatilGunleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Izinliler", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Izinliler
		{
			get
			{
				return this._Izinliler;
			}
			set
			{
				if ((this._Izinliler != value))
				{
					this.OnIzinlilerChanging(value);
					this.SendPropertyChanging();
					this._Izinliler = value;
					this.SendPropertyChanged("Izinliler");
					this.OnIzinlilerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gun", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Gun
		{
			get
			{
				return this._Gun;
			}
			set
			{
				if ((this._Gun != value))
				{
					this.OnGunChanging(value);
					this.SendPropertyChanging();
					this._Gun = value;
					this.SendPropertyChanged("Gun");
					this.OnGunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.Musteri")]
	public partial class Musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Firma;
		
		private string _Unvan;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _Email;
		
		private string _Tel1;
		
		private string _Tel2;
		
		private System.Nullable<bool> _MesaiKontrol;
		
		private System.Nullable<int> _MesaiKota;
		
		private int _FID;
		
		private string _Kaydeden;
		
		private System.Nullable<System.DateTime> _KayitTarih;
		
		private string _Degistiren;
		
		private System.Nullable<System.DateTime> _DegisTarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnUnvanChanging(string value);
    partial void OnUnvanChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTel1Changing(string value);
    partial void OnTel1Changed();
    partial void OnTel2Changing(string value);
    partial void OnTel2Changed();
    partial void OnMesaiKontrolChanging(System.Nullable<bool> value);
    partial void OnMesaiKontrolChanged();
    partial void OnMesaiKotaChanging(System.Nullable<int> value);
    partial void OnMesaiKotaChanged();
    partial void OnFIDChanging(int value);
    partial void OnFIDChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihChanged();
    partial void OnDegistirenChanging(string value);
    partial void OnDegistirenChanged();
    partial void OnDegisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnDegisTarihChanged();
    #endregion
		
		public Musteri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unvan", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Unvan
		{
			get
			{
				return this._Unvan;
			}
			set
			{
				if ((this._Unvan != value))
				{
					this.OnUnvanChanging(value);
					this.SendPropertyChanging();
					this._Unvan = value;
					this.SendPropertyChanged("Unvan");
					this.OnUnvanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(300)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(80)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel1", DbType="VarChar(15)")]
		public string Tel1
		{
			get
			{
				return this._Tel1;
			}
			set
			{
				if ((this._Tel1 != value))
				{
					this.OnTel1Changing(value);
					this.SendPropertyChanging();
					this._Tel1 = value;
					this.SendPropertyChanged("Tel1");
					this.OnTel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel2", DbType="VarChar(15)")]
		public string Tel2
		{
			get
			{
				return this._Tel2;
			}
			set
			{
				if ((this._Tel2 != value))
				{
					this.OnTel2Changing(value);
					this.SendPropertyChanging();
					this._Tel2 = value;
					this.SendPropertyChanged("Tel2");
					this.OnTel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesaiKontrol", DbType="Bit")]
		public System.Nullable<bool> MesaiKontrol
		{
			get
			{
				return this._MesaiKontrol;
			}
			set
			{
				if ((this._MesaiKontrol != value))
				{
					this.OnMesaiKontrolChanging(value);
					this.SendPropertyChanging();
					this._MesaiKontrol = value;
					this.SendPropertyChanged("MesaiKontrol");
					this.OnMesaiKontrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesaiKota", DbType="Int")]
		public System.Nullable<int> MesaiKota
		{
			get
			{
				return this._MesaiKota;
			}
			set
			{
				if ((this._MesaiKota != value))
				{
					this.OnMesaiKotaChanging(value);
					this.SendPropertyChanging();
					this._MesaiKota = value;
					this.SendPropertyChanged("MesaiKota");
					this.OnMesaiKotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FID", DbType="Int NOT NULL")]
		public int FID
		{
			get
			{
				return this._FID;
			}
			set
			{
				if ((this._FID != value))
				{
					this.OnFIDChanging(value);
					this.SendPropertyChanging();
					this._FID = value;
					this.SendPropertyChanged("FID");
					this.OnFIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degistiren", DbType="VarChar(5)")]
		public string Degistiren
		{
			get
			{
				return this._Degistiren;
			}
			set
			{
				if ((this._Degistiren != value))
				{
					this.OnDegistirenChanging(value);
					this.SendPropertyChanging();
					this._Degistiren = value;
					this.SendPropertyChanged("Degistiren");
					this.OnDegistirenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DegisTarih
		{
			get
			{
				return this._DegisTarih;
			}
			set
			{
				if ((this._DegisTarih != value))
				{
					this.OnDegisTarihChanging(value);
					this.SendPropertyChanging();
					this._DegisTarih = value;
					this.SendPropertyChanged("DegisTarih");
					this.OnDegisTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ong.ProjeForm")]
	public partial class ProjeForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Firma;
		
		private string _Proje;
		
		private string _Form;
		
		private string _Sorumlu;
		
		private string _KarsiSorumlu;
		
		private string _Aciklama;
		
		private System.Nullable<bool> _MesaiKontrol;
		
		private System.Nullable<int> _MesaiKota;
		
		private System.Nullable<int> _PID;
		
		private System.Nullable<short> _Durum;
		
		private string _Kaydeden;
		
		private System.Nullable<System.DateTime> _KayitTarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnProjeChanging(string value);
    partial void OnProjeChanged();
    partial void OnFormChanging(string value);
    partial void OnFormChanged();
    partial void OnSorumluChanging(string value);
    partial void OnSorumluChanged();
    partial void OnKarsiSorumluChanging(string value);
    partial void OnKarsiSorumluChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnMesaiKontrolChanging(System.Nullable<bool> value);
    partial void OnMesaiKontrolChanged();
    partial void OnMesaiKotaChanging(System.Nullable<int> value);
    partial void OnMesaiKotaChanged();
    partial void OnPIDChanging(System.Nullable<int> value);
    partial void OnPIDChanged();
    partial void OnDurumChanging(System.Nullable<short> value);
    partial void OnDurumChanged();
    partial void OnKaydedenChanging(string value);
    partial void OnKaydedenChanged();
    partial void OnKayitTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnKayitTarihChanged();
    #endregion
		
		public ProjeForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Proje
		{
			get
			{
				return this._Proje;
			}
			set
			{
				if ((this._Proje != value))
				{
					this.OnProjeChanging(value);
					this.SendPropertyChanging();
					this._Proje = value;
					this.SendPropertyChanged("Proje");
					this.OnProjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorumlu", DbType="VarChar(5)")]
		public string Sorumlu
		{
			get
			{
				return this._Sorumlu;
			}
			set
			{
				if ((this._Sorumlu != value))
				{
					this.OnSorumluChanging(value);
					this.SendPropertyChanging();
					this._Sorumlu = value;
					this.SendPropertyChanged("Sorumlu");
					this.OnSorumluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KarsiSorumlu", DbType="VarChar(50)")]
		public string KarsiSorumlu
		{
			get
			{
				return this._KarsiSorumlu;
			}
			set
			{
				if ((this._KarsiSorumlu != value))
				{
					this.OnKarsiSorumluChanging(value);
					this.SendPropertyChanging();
					this._KarsiSorumlu = value;
					this.SendPropertyChanged("KarsiSorumlu");
					this.OnKarsiSorumluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(300)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesaiKontrol", DbType="Bit")]
		public System.Nullable<bool> MesaiKontrol
		{
			get
			{
				return this._MesaiKontrol;
			}
			set
			{
				if ((this._MesaiKontrol != value))
				{
					this.OnMesaiKontrolChanging(value);
					this.SendPropertyChanging();
					this._MesaiKontrol = value;
					this.SendPropertyChanged("MesaiKontrol");
					this.OnMesaiKontrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesaiKota", DbType="Int")]
		public System.Nullable<int> MesaiKota
		{
			get
			{
				return this._MesaiKota;
			}
			set
			{
				if ((this._MesaiKota != value))
				{
					this.OnMesaiKotaChanging(value);
					this.SendPropertyChanging();
					this._MesaiKota = value;
					this.SendPropertyChanged("MesaiKota");
					this.OnMesaiKotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int")]
		public System.Nullable<int> PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="SmallInt")]
		public System.Nullable<short> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this.OnKaydedenChanging(value);
					this.SendPropertyChanging();
					this._Kaydeden = value;
					this.SendPropertyChanged("Kaydeden");
					this.OnKaydedenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> KayitTarih
		{
			get
			{
				return this._KayitTarih;
			}
			set
			{
				if ((this._KayitTarih != value))
				{
					this.OnKayitTarihChanging(value);
					this.SendPropertyChanging();
					this._KayitTarih = value;
					this.SendPropertyChanged("KayitTarih");
					this.OnKayitTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GorevCalisma_TakvimiResult
	{
		
		private string _Kaydeden;
		
		private System.Nullable<int> _CalismaSure;
		
		private System.Nullable<int> _Saat;
		
		private System.Nullable<int> _Dakika;
		
		private string _Firma;
		
		private string _Proje;
		
		private System.DateTime _Tarih;
		
		private string _TarihStr;
		
		public GorevCalisma_TakvimiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaydeden", DbType="VarChar(5)")]
		public string Kaydeden
		{
			get
			{
				return this._Kaydeden;
			}
			set
			{
				if ((this._Kaydeden != value))
				{
					this._Kaydeden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalismaSure", DbType="Int")]
		public System.Nullable<int> CalismaSure
		{
			get
			{
				return this._CalismaSure;
			}
			set
			{
				if ((this._CalismaSure != value))
				{
					this._CalismaSure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saat", DbType="Int")]
		public System.Nullable<int> Saat
		{
			get
			{
				return this._Saat;
			}
			set
			{
				if ((this._Saat != value))
				{
					this._Saat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dakika", DbType="Int")]
		public System.Nullable<int> Dakika
		{
			get
			{
				return this._Dakika;
			}
			set
			{
				if ((this._Dakika != value))
				{
					this._Dakika = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this._Firma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Proje
		{
			get
			{
				return this._Proje;
			}
			set
			{
				if ((this._Proje != value))
				{
					this._Proje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this._Tarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarihStr", DbType="NVarChar(92)")]
		public string TarihStr
		{
			get
			{
				return this._TarihStr;
			}
			set
			{
				if ((this._TarihStr != value))
				{
					this._TarihStr = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
